MenschAergereDichNicht.out: CppMenschAergereDichNicht.o
	g++ -std=c++11 -o MenschAergereDichNicht.out CppMenschAergereDichNicht.o
CppMenschAergereDichNicht.o: CppMenschAergereDichNicht.cpp
	g++ -std=c++11 -o CppMenschAergereDichNicht.o -c CppMenschAergereDichNicht.cpp
run: MenschAergereDichNicht.out
	./MenschAergereDichNicht.out
clean:
	rm *.out *.o